src/main/java/io/vertx/codegen/ClassModel.java, src/main/java/io/vertx/codegen/CodeGenProcessor.java, src/main/java/io/vertx/codegen/Helper.java, src/main/java/io/vertx/codegen/MethodInfo.java, src/main/java/io/vertx/codegen/ParamInfo.java, src/main/java/io/vertx/codegen/ProxyMethodInfo.java, src/main/java/io/vertx/codegen/ProxyModel.java, src/main/java/io/vertx/codegen/doc/Comment.java, src/main/java/io/vertx/codegen/doc/Doc.java, src/main/java/io/vertx/codegen/doc/Tag.java, src/main/java/io/vertx/codegen/doc/Token.java, src/test/java/io/vertx/test/codegen/CommentTest.java, src/test/java/io/vertx/test/codegen/GeneratorTest.java, src/test/java/io/vertx/test/codegen/HelperTest.java, src/test/java/io/vertx/test/codegen/Utils.java, src/test/java/io/vertx/test/codegen/doc/LinkLabel.java, src/test/java/io/vertx/test/codegen/doc/LinkToMethodInSameType.java, src/test/java/io/vertx/test/codegen/doc/LinkToSameType.java, src/test/java/io/vertx/test/codegen/doc/package-info.java, src/test/java/io/vertx/test/codegen/testapi/InterfaceWithComments.java
=> Documentation work

src/main/java/io/vertx/core/json/JsonArray.java, src/main/java/io/vertx/core/json/JsonObject.java, src/tck/java/io/vertx/codegen/testmodel/TestInterface.java, src/tck/java/io/vertx/codegen/testmodel/TestInterfaceImpl.java
Signed-off-by: Sean Fitts <smfitts@gmail.com>
=> Add methods for testing of nested JsonObject/JsonArray structures.

src/main/java/io/vertx/codegen/ClassModel.java, src/main/java/io/vertx/codegen/CodeGen.java, src/main/java/io/vertx/codegen/Compiler.java, src/main/java/io/vertx/codegen/DataObjectModel.java, src/main/java/io/vertx/codegen/Generator.java, src/main/java/io/vertx/codegen/ModuleModel.java, src/main/java/io/vertx/codegen/PackageModel.java, src/main/java/io/vertx/codegen/TypeInfo.java, src/test/java/io/vertx/test/codegen/GeneratorTest.java, src/test/java/io/vertx/test/codegen/ModuleTest.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithInvalidWildcardTypeArg.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithValidVoidTypeArg.java
A few Improvements for Ceylon lang and general improvements.
=> Improvements for ceylon

src/main/asciidoc/java/index.adoc, src/main/java/io/vertx/codegen/ClassModel.java, src/main/java/io/vertx/codegen/package-info.java, src/main/java/io/vertx/core/AsyncResult.java, src/tck/java/io/vertx/codegen/testmodel/TestInterface.java, src/tck/java/io/vertx/codegen/testmodel/TestInterfaceImpl.java, src/test/java/io/vertx/test/codegen/ClassTest.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithHandlerAsyncResultReturn.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithHandlerReturn.java
See https://github.com/vert-x3/issues/issues/85
=> Codegen handler return support

src/main/asciidoc/java/index.adoc, src/main/java/io/vertx/codegen/ClassModel.java, src/main/java/io/vertx/codegen/CodeGenProcessor.java, src/main/java/io/vertx/codegen/package-info.java, src/main/java/io/vertx/codegen/type/ClassKind.java, src/tck/java/io/vertx/codegen/testmodel/FunctionParamTCK.java, src/tck/java/io/vertx/codegen/testmodel/FunctionParamTCKImpl.java, src/test/java/io/vertx/test/codegen/ClassTest.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithFunctionInHandler.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithFunctionInHandlerAsyncResult.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithInvalidFunctionParam1.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithInvalidFunctionParam2.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithInvalidFunctionParam3.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithInvalidFunctionParam4.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithInvalidFunctionParam5.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithInvalidFunctionParam6.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithInvalidFunctionParam7.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithInvalidFunctionParam8.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithValidFunctionParams.java
Support for codegen function params:
```
void filter(Function<String, Boolean> predicate);
```
please review.
=> Function params

src/main/java/io/vertx/codegen/ClassModel.java
Sorry, just figured out this morning with some coffee :)
Same result (works on JDT), but proper fix instead of hacking....
=> Replace hack with proper API use

src/main/java/io/vertx/codegen/DataObjectModel.java, src/main/java/io/vertx/codegen/Helper.java, src/main/java/io/vertx/codegen/ProxyModel.java, src/test/java/io/vertx/test/codegen/ProxyTest.java, src/test/java/io/vertx/test/codegen/proxytestapi/ProxyDataObjectWithParentOverride.java, src/test/java/io/vertx/test/codegen/proxytestapi/ValidProxy.java
=> Proxies dataobject param cannot extend jsonifiable class

pom.xml
This PR fixes https://github.com/vert-x3/vertx-codegen/issues/143.
=> Updated Jackson to 2.9.0.

src/main/java/io/vertx/codegen/CodeGen.java, src/main/java/io/vertx/codegen/CodeGenProcessor.java, src/main/java/io/vertx/codegen/Generator.java, src/main/java/io/vertx/codegen/Helper.java, src/main/java/io/vertx/codegen/type/TypeUse.java, src/test/java/io/vertx/test/codegen/ClassNullableTest.java
@codepitbull can you test this with your case ?
=> Processor loads classpath correctly

src/main/java/io/vertx/codegen/Case.java
the comment is copy from MethodKind
=> Fix typo on comment

src/main/java/io/vertx/codegen/CodeGenProcessor.java, src/test/java/io/vertx/test/codegen/CodeGeneratorTest.java, src/test/java/io/vertx/test/codegen/generator/MyGenerator.java, src/test/java/io/vertx/test/codegen/generator/MyGeneratorLoader.java, src/test/resources/META-INF/services/io.vertx.codegen.GeneratorLoader
Support for loading custom GeneratorLoader and Generator using ServiceLoader
=> Support for loading custom GeneratorLoader and Generator using ServiceLoader

src/main/java/io/vertx/codegen/CodeGenProcessor.java
ClassLoader using CodeGenProcessor.class.getClassLoader() like DocGenProcessor
=> Failed to Load GeneratorLoader with Plugin's ClassLoader

pom.xml, src/main/java/io/vertx/codegen/type/MirrorTypeInternal.java, src/main/java/io/vertx/codegen/type/ReflectTypeInternal.java, src/main/java/io/vertx/codegen/type/TreeTypeInternal.java, src/main/java/io/vertx/codegen/type/TypeInternalProviders.java, src/main/java/io/vertx/codegen/type/TypeUse.java, src/main/java9/io/vertx/codegen/type/TypeInternalProviders.java
=> Use multi release jar so TreeTypeInternal is not visible with JDK9

src/main/java/io/vertx/codegen/CodeGen.java, src/test/java/io/vertx/test/codegen/GeneratorHelper.java
Made GeneratorHelper extensible to use it for service proxy and web api service proxy.
=> Made GeneratorHelper extensible

README.md, src/test/testgen1/templates/dataObjectGen.templ
So this PR gonna fix the documents and test generated templ
including:
1) add has empty constructor field
2) writer/reader methods -> setter, adder & getter methods
=> hasEmptyConstructor property is actually added in the code but the doc is still old

src/main/java/io/vertx/codegen/ClassModel.java, src/main/java/io/vertx/codegen/DataObjectModel.java, src/test/java/io/vertx/test/codegen/CodeGeneratorTest.java, src/test/java/io/vertx/test/codegen/DocTest.java, src/test/java/io/vertx/test/codegen/doc/NoDoc.java
Added test for no doc corner case
Signed-off-by: francesco <francescoguard@gmail.com>
=> Fixed npe in doc parsing in class model and data object

pom.xml
This is related to [issue 172](https://github.com/vert-x3/vertx-rx/issues/172) in vertx-rx repository
=> vertx-codegen OSGI module can't be resolved in Apache Felix

src/main/java/io/vertx/codegen/ClassModel.java, src/main/java/io/vertx/codegen/type/ApiTypeInfo.java, src/main/java/io/vertx/codegen/type/TypeMirrorFactory.java, src/main/java/io/vertx/codegen/type/TypeReflectionFactory.java, src/test/java/io/vertx/test/codegen/ClassTest.java, src/test/java/io/vertx/test/codegen/TypeInfoTest.java
=> Move interface type arg info to ClassModel

src/main/java/io/vertx/codegen/ClassModel.java, src/test/java/io/vertx/test/codegen/ClassTest.java, src/test/java/io/vertx/test/codegen/testapi/InterfaceWithFunctionApiSuperType.java, src/test/java/io/vertx/test/codegen/testapi/InterfaceWithFunctionStringSuperType.java, src/test/java/io/vertx/test/codegen/testapi/InterfaceWithIllegalArgumentFunctionSuperType.java, src/test/java/io/vertx/test/codegen/testapi/InterfaceWithIllegalArgumentIterableSuperType.java, src/test/java/io/vertx/test/codegen/testapi/InterfaceWithIterableApiSuperType.java, src/test/java/io/vertx/test/codegen/testapi/InterfaceWithIterableStringSuperType.java, src/test/java/io/vertx/test/codegen/testapi/InterfaceWithNonGenSuperType.java, src/test/java/io/vertx/test/codegen/testapi/InterfaceWithParameterizedFunctionSuperType.java, src/test/java/io/vertx/test/codegen/testapi/InterfaceWithParameterizedIterableSuperType.java, src/test/java/io/vertx/test/codegen/testapi/NonGenSuperType.java
=> Iterable, Iterator and Function support

pom.xml, src/main/java/io/vertx/codegen/generators/mvel/MvelCodeGeneratorLoader.java
Codegen brings Jackson databind dependency in stack modules.
This prevents to find potential issues for users who will not add databind to their classpath.
=> Removed dependency on Jackson databind

src/main/asciidoc/index.adoc, src/main/java/io/vertx/codegen/generators/mvel/MvelCodeGeneratorLoader.java
Ruby and Service Proxy projects must be updated after this one is merged
=> MvelCodeGeneratorLoader: standardize on templateFilename and filename attribute names

src/main/java/io/vertx/codegen/CodeGenProcessor.java
Signed-off-by: Cristiano V. Gavião <cvgaviao@gmail.com>
A fix for #299
=> fix for #299

src/main/asciidoc/index.adoc, src/main/java/io/vertx/codegen/ClassModel.java, src/main/java/io/vertx/codegen/MethodInfo.java, src/main/java/io/vertx/codegen/MethodKind.java, src/main/java/io/vertx/codegen/ModuleInfo.java, src/main/java/io/vertx/codegen/ModuleModel.java, src/main/java/io/vertx/codegen/annotations/ModuleGen.java, src/main/java/io/vertx/codegen/type/TypeMirrorFactory.java, src/main/java/io/vertx/codegen/type/TypeReflectionFactory.java, src/test/java/io/vertx/test/codegen/ClassNullableTest.java, src/test/java/io/vertx/test/codegen/ClassTest.java, src/test/java/io/vertx/test/codegen/nextgen/MethodWithCallback.java, src/test/java/io/vertx/test/codegen/nextgen/MethodWithFutures.java, src/test/java/io/vertx/test/codegen/nextgen/package-info.java
see also
- https://github.com/vert-x3/vertx-rx/pull/254
- https://github.com/vert-x3/vertx-service-proxy/pull/125
=> Future returning signature for codegen

README.md
=> fix: default methods are not permitted

vertx-codegen-processor/src/main/java/io/vertx/codegen/EnumModel.java, vertx-codegen-protobuf/src/converters/generated/dataobjects.proto, vertx-codegen-protobuf/src/converters/generated/io/vertx/test/codegen/converter/AddressProtoConverter.java, vertx-codegen-protobuf/src/converters/generated/io/vertx/test/codegen/converter/RecursiveItemProtoConverter.java, vertx-codegen-protobuf/src/converters/generated/io/vertx/test/codegen/converter/UserProtoConverter.java, vertx-codegen-protobuf/src/converters/java/io/vertx/test/codegen/converter/EnumType.java, vertx-codegen-protobuf/src/converters/java/io/vertx/test/codegen/converter/User.java, vertx-codegen-protobuf/src/main/asciidoc/index.adoc, vertx-codegen-protobuf/src/main/java/io/vertx/codegen/protobuf/generator/DataObjectProtobufGen.java, vertx-codegen-protobuf/src/main/java/io/vertx/codegen/protobuf/generator/ProtoFileGen.java, vertx-codegen-protobuf/src/main/java/io/vertx/codegen/protobuf/generator/ProtoProperty.java, vertx-codegen-protobuf/src/test/java/io/vertx/test/codegen/protobuf/ProtoConverterTest.java
Implement #361
Example:
```Java
@VertxGen
@ProtobufGen
public enum Colour {
RED,
GREEN,
BLUE
}
```
=> add enum type support for protobuf-codegen

vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/Processor.java
The processor generator loader will fail when a generator is declared but cannot be class loaded, e.g. compiling a generator which contains processor annotations (e.g. @VertxGen) fails when the generator is declared as a service in META-INF. While this is actually correct, we should tolerate this situation and continue generator loading with a warn in order to allow this case for code generators.
Modify the generator loading of the processor to use plain iteration instead of java streams and catch service configuration errors to continue loading of other generators and not failing the current processor.
=> Let the processor tolerate generator service loading failures
