src/main/java/io/vertx/codegen/ClassModel.java, src/main/java/io/vertx/codegen/ProxyModel.java, src/tck/java/io/vertx/codegen/testmodel/TestInterface.java, src/tck/java/io/vertx/codegen/testmodel/TestInterfaceImpl.java, src/test/java/io/vertx/test/codegen/GeneratorTest.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithValidHandlerAsyncResultParams.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithValidListParams.java, src/test/java/io/vertx/test/codegen/testapi/MethodWithValidSetParams.java
Added support for list and set of @DataObject in method parameters and async result handler.
This pull request depends on https://github.com/vert-x3/vertx-service-proxy/pull/12
=> Added support for list and set of @DataObject

src/tck/java/io/vertx/codegen/testmodel/TestInterface.java, src/tck/java/io/vertx/codegen/testmodel/TestInterfaceImpl.java
Add tests to codegen TCK about method receiving list and set of data objects as parameter. The reason behind this PR is a bug in groovy-lang (missing import in this case).
=> Add tests to CodeGen TCK about method receiving a list or a set of data objects

src/main/java/io/vertx/codegen/Helper.java, src/main/java/io/vertx/codegen/TypeInfo.java, src/main/java/io/vertx/core/streams/ReadStream.java, src/test/java/io/vertx/test/codegen/TypeInfoTest.java, src/test/java/io/vertx/test/codegen/testtype/ApiHolder.java, src/test/java/io/vertx/test/codegen/testtype/ApiObject.java, src/test/java/io/vertx/test/codegen/testtype/AsyncHolder.java, src/test/java/io/vertx/test/codegen/testtype/BasicHolder.java, src/test/java/io/vertx/test/codegen/testtype/CollectionHolder.java, src/test/java/io/vertx/test/codegen/testtype/DataObjectHolder.java, src/test/java/io/vertx/test/codegen/testtype/EnumHolder.java, src/test/java/io/vertx/test/codegen/testtype/HandlerHolder.java, src/test/java/io/vertx/test/codegen/testtype/JsonHolder.java, src/test/java/io/vertx/test/codegen/testtype/OtherHolder.java, src/test/java/io/vertx/test/codegen/testtype/StreamHolder.java, src/test/java/io/vertx/test/codegen/testtype/ThrowableHolder.java, src/test/java/io/vertx/test/codegen/testtype/TypeParamHolder.java, src/test/java/io/vertx/test/codegen/testtype/VoidHolder.java
A set of TypeInfo improvements, mostly missing tests and the TypeInfo based on java.lang.reflect was missing some handling.
=> Improve TypeInfo test to also test the model type info construction

src/main/asciidoc/java/index.adoc, src/main/java/io/vertx/codegen/DataObjectModel.java, src/main/java/io/vertx/codegen/PropertyInfo.java, src/main/java/io/vertx/codegen/PropertyKind.java, src/main/java/io/vertx/codegen/package-info.java, src/test/java/io/vertx/test/codegen/DataObjectTest.java, src/test/java/io/vertx/test/codegen/testdataobject/PropertyGetters.java, src/test/java/io/vertx/test/codegen/testdataobject/PropertyGettersAdders.java, src/test/java/io/vertx/test/codegen/testdataobject/PropertySetGettersSetters.java, src/test/java/io/vertx/test/codegen/testdataobject/PropertySetSetters.java
Improvements created for improving the support of vertx-sql-common `UpdateResult` and `ResultSet` data objects:
- data object model is now aware of getters without setter nor adder
- support for Set<T> type as we do use it in some data objects
=> Data object improvements

src/main/java/io/vertx/codegen/ProxyModel.java, src/test/java/io/vertx/test/codegen/ProxyTest.java, src/test/java/io/vertx/test/codegen/proxytestapi/ProxyDataObjectParent.java, src/test/java/io/vertx/test/codegen/proxytestapi/ProxyDataObjectWithParent.java, src/test/java/io/vertx/test/codegen/proxytestapi/ValidProxy.java
This addition makes it possible to put the toJson method in the (abstract) parent of a DataObject.
=> Added support for supertypes with toJson() method

src/main/java/io/vertx/codegen/Template.java
I've added this on my windows system to handle the differences in line endings gracefully. 
`mvn install` that also includes test ran successfully.
=> handle system dependent line endings gracefully

src/main/java/io/vertx/codegen/CodeGenProcessor.java
I found that when running the asciidoc generation on vertx-core the dataobjects.adoc and enums.adoc didn't have a stable sorting - at least they created on my PC a different sorting than the one in the repository. 
This PR suggests a sorting by SimpleName as I think it would be appropriate for cli-for-java.adoc, dataobjects.adoc, and enums.adoc in the context of vertx-core. 
When this PR is accepted, the documents in vertx-core should be re-created.
=> add stable sorting by simple name for incremental processing

src/main/java/io/vertx/codegen/ClassModel.java
As Eclipse JDT `PackageElement` emits "package XXX" instead of just "XXX", add a simple check and fix to make the codegen work with Eclipse compiler.
Manually validated the change locally, and generated code is correct.
=> Fix for #81

src/main/java/io/vertx/codegen/CodeGenProcessor.java
Remove duplicate DataObject.class
=> DataObject.class appears twice in getSupportedAnnotationTypes

src/tck/java/io/vertx/codegen/testmodel/RefedInterface1Impl.java
I need RefedInterface1Impl.equals to be null safe for a few unit-tests for vertx-scala-lang.
=> RefedInterface1Impl.equals is now null safe

src/main/java/io/vertx/codegen/doc/Doc.java, src/test/java/io/vertx/test/codegen/DocTest.java
Fixed a regular expression in Doc class to take into account methods with no Javadoc text (tags only).
As a consequence, the firstSentence text is now empty, instead of being the Javadoc block as is.
If this is merged, we would no longer see `@author` text (see http://vertx.io/docs/vertx-redis-client/enums.html or http://vertx.io/docs/vertx-redis-client/dataobjects.html)
Or `@return` (see `errorCode` description in http://vertx.io/docs/vertx-core/dataobjects.html#GoAway)
For the former, it seems good to me. For the latter, updating the templates would be better.
Thoughts?
=> Fixes #95 Duplicate return tag

src/tck/java/io/vertx/codegen/testmodel/DataObjectWithLists.java, src/tck/java/io/vertx/codegen/testmodel/DataObjectWithMaps.java
DataObjectWithLists and DataObjectWithMaps incorrectly tried to cast some JsonObjects to Map and JsonArrays to List.
=> Fixed casting errors in DataObjectTCK

src/main/java/io/vertx/core/json/JsonArray.java, src/main/java/io/vertx/core/json/JsonObject.java, src/tck/java/io/vertx/codegen/testmodel/DataObjectWithLists.java, src/tck/java/io/vertx/codegen/testmodel/DataObjectWithMaps.java
This produced inconsistencies when the backing list/map contained json wrappers
such as JsonArray/JsonObject or backing List/Map. Use the new stream() method
to always view wrapped values to remove inconsistencies.
=> Fixed bug in traversal of json arrays/maps

pom.xml, src/main/java/io/vertx/codegen/ClassModel.java, src/main/java/io/vertx/codegen/CodeGen.java, src/main/java/io/vertx/codegen/CodeGenProcessor.java, src/main/java/io/vertx/codegen/Helper.java, src/main/java/io/vertx/codegen/ParamInfo.java, src/main/java/io/vertx/codegen/ProxyModel.java, src/main/java/io/vertx/codegen/type/TreeTypeInternal.java, src/main/java/io/vertx/codegen/type/TypeUse.java, src/test/java/io/vertx/test/codegen/ClassNullableTest.java, src/test/java/io/vertx/test/codegen/testapi/nullable/MethodWithCovariantNullableReturn.java, src/test/java/io/vertx/test/codegen/testapi/nullable/MethodWithNullableInheritedParams.java, src/test/java/io/vertx/test/codegen/testapi/nullable/MethodWithNullableParams.java, src/test/java/io/vertx/test/codegen/testapi/nullable/MethodWithNullableReturns.java, src/test/java/io/vertx/test/codegen/testapi/nullable/MethodWithNullableStringHandlerAsyncResult.java
This PR provides support for obtaining better `@Nullable` information in codegen types. The current support relies on the `javax.lang.model` which is not complete and fails to obtain the annotation with parameterized types (e.g `Handler<AsyncResult<@Nullable String>>`). This is not really a bug but rather an incomplete implementation of the API that is implemented in Java 9.
This PR relies on internal types of the compiler to extract the relevant information. As this is Java 8 specific, the implementation falls back on the `javax.lang.model` API when the internal API is not available and therefore should work with Java 9. When Java 9 will be released we will make sure it works as expected. Note this is not a runtime issue but rather a codegen compile time issue to address.
=> Type use fix

README.md
There were a few instances of B and J used instead of Basic and Json. Changed those for better readability.
=> Updated README to use the explicit set names

README.md, pom.xml, src/main/java/io/vertx/codegen/CodeGenProcessor.java, src/main/java/io/vertx/codegen/CodeGenerator.java, src/test/java/io/vertx/test/codegen/CodeGeneratorTest.java, src/test/testgen6/codegen.json, src/test/testgen6/templates/multiple_types.templ
A generator definiton should allow multiple types to be matched against the same generator.
This would allow to have the same template be used for classes and dataobjects and, combined with incremental, to collect everything in one resulting file (e.g. a Scala package object)
=> Add ability to use one generator for multiple kinds

src/main/java/io/vertx/codegen/generators/dataobjecthelper/DataObjectHelperGen.java, src/test/generated/io/vertx/test/codegen/converter/ChildInheritingDataObjectConverter.java, src/test/generated/io/vertx/test/codegen/converter/ChildNotInheritingDataObjectConverter.java, src/test/generated/io/vertx/test/codegen/converter/DataObjectWithGenIgnoreConverter.java, src/test/generated/io/vertx/test/codegen/converter/ParentDataObjectConverter.java, src/test/generated/io/vertx/test/codegen/converter/SetterAdderDataObjectConverter.java, src/test/generated/io/vertx/test/codegen/converter/TestDataObjectConverter.java, src/test/java/io/vertx/test/codegen/converter/DataObjectTest.java, src/test/java/io/vertx/test/codegen/converter/DataObjectWithGenIgnore.java
Add equals & hashCode helper methods for generated DataObject annotated classes.
Signed-off-by: Farid Zakaria <farid.m.zakaria@gmail.com>
=> Add equals & hashCode helper methods for DataObjectConverter

src/main/java/io/vertx/codegen/generators/cheatsheet/DataObjectCheatsheetGen.java, src/main/java/io/vertx/codegen/generators/cheatsheet/EnumCheatsheetGen.java
This fixes the cheatsheet generators (dataobject & enum). Obviously the hard-coded paths to `asciidoc` need to be replaced but I'm not sure where you want to take the path from. Maybe the `docgen.output` option?
=> fix cheatsheet generators

src/main/java/io/vertx/codegen/type/DataObjectTypeInfo.java, src/main/java/io/vertx/codegen/type/TypeMirrorFactory.java, src/main/java/io/vertx/codegen/type/TypeReflectionFactory.java
While generating the wrappers for the pg-client I hit the issue that I need to differentiate between three variations of DataObjects:
- concrete ones
- abstract classes
- interfaces
So far only the first two were correctly covered since DataObjectTypeInfo only provided isAbstract.
I simply added the missing information as a isInterface check on DataObjectTypeInfo.
=> Isinterface for dos

src/converters/generated/io/vertx/test/codegen/converter/ChildInheritingDataObjectConverter.java, src/converters/generated/io/vertx/test/codegen/converter/ChildNotInheritingDataObjectConverter.java, src/converters/generated/io/vertx/test/codegen/converter/ConverterGeneratesDeserializerWithFromJsonDataObjectConverter.java, src/converters/generated/io/vertx/test/codegen/converter/ConverterGeneratesSerializerWithToJsonDataObjectConverter.java, src/converters/generated/io/vertx/test/codegen/converter/ParentDataObjectConverter.java, src/converters/generated/io/vertx/test/codegen/converter/SetterAdderDataObjectConverter.java, src/converters/generated/io/vertx/test/codegen/converter/SnakeFormattedDataObjectConverter.java, src/converters/generated/io/vertx/test/codegen/converter/TestDataObjectConverter.java, src/main/java/io/vertx/codegen/generators/dataobjecthelper/DataObjectHelperGen.java, src/main/java/io/vertx/core/json/impl/JsonUtil.java, src/tck/generated/io/vertx/codegen/testmodel/DataObjectWithBufferConverter.java, src/tck/generated/io/vertx/codegen/testmodel/DataObjectWithListAddersConverter.java, src/tck/generated/io/vertx/codegen/testmodel/DataObjectWithListsConverter.java, src/tck/generated/io/vertx/codegen/testmodel/DataObjectWithMapAddersConverter.java, src/tck/generated/io/vertx/codegen/testmodel/DataObjectWithMapsConverter.java, src/tck/generated/io/vertx/codegen/testmodel/DataObjectWithNestedBufferConverter.java, src/tck/generated/io/vertx/codegen/testmodel/DataObjectWithOnlyJsonObjectConstructorConverter.java, src/tck/generated/io/vertx/codegen/testmodel/DataObjectWithRecursionConverter.java, src/tck/generated/io/vertx/codegen/testmodel/DataObjectWithValuesConverter.java, src/test/java/io/vertx/test/codegen/converter/DataObjectTest.java
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
Motivation:
Core has been changed here:
https://github.com/eclipse-vertx/vert.x/pull/3197
To correctly implement the RFC7493
However codegen still used the wrong codec and there was no way to support the correct one.
This PR fixes the codegen to use the exact same codec as `core` and also respect the config flag to switch to the `old/legacy` codec if core also so does.
=> Fix base64 codec

src/main/java/io/vertx/codegen/type/TypeMirrorFactory.java, src/tck/java/io/vertx/codegen/testmodel/NullableTCK.java, src/tck/java/io/vertx/codegen/testmodel/NullableTCKImpl.java
Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>
When a type included an annotation such as @NonNull then TypeMirrorFactory tried to find a mapper using type.toString().
type.toString() included the annotation in the name as well which resulted in failing to find the appropriate mapper.
With these change the serializers / deserializers are found using the fqdn of the type only
=> Ignore type annotations when searching for serializers / deserializers

src/main/java/io/vertx/codegen/CodeGen.java
Signed-off-by: Jérémy Florte <jeremy.florte@leroymerlin.fr>
Motivation:
Using a recent JDK (16), code generation does not work on project using modules (i.e java modules, declared in module-info.java files).
The aim of this P.R is to fix code generation, adding a control to a previous fix made for JDK 11 that used to throw a NPE (from JDK code) when accessing package elements. JDK 16 does not throw a NPE but returns `null` which was not handled and thus raised a NPE from the project code itself.
A test case would have been useful but it would require the project to compile with JDK 16, not true today.
The P.R code has been tested with JDK 11 and 16 on sample project provided in declared issue and initial use case project. 
_NB: conformance requirements done_
=> Issue#327 - Code generation not working with modules + JDK 16 

src/main/java/io/vertx/codegen/TypeValidator.java, src/test/java/io/vertx/test/codegen/ClassTest.java, src/test/java/io/vertx/test/codegen/testapi/kotlin/Companion.java, src/test/java/io/vertx/test/codegen/testapi/kotlin/InterfaceWithCompanionObject.java, src/test/java/io/vertx/test/codegen/testapi/kotlin/InterfaceWithUnrelatedCompanionClass.java
This is a duplicate of #229, which went stale and had a messy commit history.
> Simple workaround for [vert-x3/vertx-lang-kotlin#93](https://github.com/vert-x3/vertx-lang-kotlin/issues/93).
> 
> LMK if there's a better/more appropriate fix.
FYI @vietj
=> Fix regression for Kotlin companion objects

src/main/java/io/vertx/codegen/ClassModel.java, src/main/java/io/vertx/codegen/MethodInfo.java, src/test/java/io/vertx/test/codegen/OverrideTest.java, src/test/java/io/vertx/test/codegen/testapi/OverrideA.java, src/test/java/io/vertx/test/codegen/testapi/OverrideB.java
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
Motivation:
When working with codegen it is useful to know when a method to be generated overrides a base class/interface method.
Now that typescript supports this too, we can add more type information to `es4x` or any of the other `codegen` generators.
This change should not affect any existing generator as it doesn't introduce any breaking change, and generators can now make use of the `isMethodOverride()` flag in `MethodInfo` to further customize the generated code as needed.
=> Allow accessing the @Override annotation from codegen

src/main/java/io/vertx/codegen/CodeGenProcessor.java
Motivation:
fixes https://github.com/eclipse-vertx/vertx-codegen/issues/346
I couldn't find a dynamic solution to all Kapt builds so I created a solution that strictly solves default Kapt setups. It fixes the problem I mention in #346 and could be expanded for more setups.
=> support default kapt builds

src/main/java/io/vertx/codegen/CodeGenProcessor.java
Motivation:
Sorry, forgot about Windows paths. Thankfully it's not a regression as Kapt builds simply continued not to work on Windows. This fixes that issue.
=> fix: add windows support to default kapt builds

src/main/java/io/vertx/codegen/ClassModel.java, src/main/java/io/vertx/codegen/ModuleInfo.java, src/main/java/io/vertx/codegen/ModuleModel.java, src/main/java/io/vertx/codegen/annotations/ModuleGen.java, src/main/java/io/vertx/codegen/type/TypeMirrorFactory.java, src/main/java/io/vertx/codegen/type/TypeReflectionFactory.java
This is a temporary option, that will get removed later after callback cleanup.
=> Add option to fail the build when a callback method is not deprecated

vertx-codegen-processor/src/main/java/io/vertx/codegen/DataObjectModel.java, vertx-codegen-processor/src/test/java/io/vertx/test/codegen/DataObjectTest.java
The processor for data objects does not converse the natural order of the declarations provided by the annotation processor element. In order to allows users reason about protobuf generation where the order matters, we need this order to be preserved.
Update the DataObjectModel implementation to conserve the declaration order as provided by the annotation processor. This changes the existing behaviour that was sorting the elements using their name as sorting element.
=> Preserve declaration order for data object properties.

vertx-codegen-protobuf/src/converters/generated/dataobjects.proto, vertx-codegen-protobuf/src/converters/generated/io/vertx/test/codegen/converter/UserProtoConverter.java, vertx-codegen-protobuf/src/converters/java/io/vertx/test/codegen/converter/User.java, vertx-codegen-protobuf/src/main/java/io/vertx/codegen/protobuf/generator/ProtoFileGen.java, vertx-codegen-protobuf/src/main/java/io/vertx/codegen/protobuf/generator/ProtoProperty.java, vertx-codegen-protobuf/src/main/resources/proto/vertx-struct.proto, vertx-codegen-protobuf/src/test/java/io/vertx/test/codegen/protobuf/GoogleStructProtoTest.java, vertx-codegen-protobuf/src/test/java/io/vertx/test/codegen/protobuf/ProtoConverterTest.java, vertx-codegen-protobuf/src/test/java/io/vertx/test/codegen/protobuf/VertxStructProtoTest.java
`JsonArray` field type is only handled by `JsonObject`. This PR adds support for handling a `JsonArray` field when it is defined in a `DataObject` POJO.
=> BugFix: add support for JsonArray field defined in DataObject

src/main/asciidoc/index.adoc, src/main/java/io/vertx/codegen/DataObjectModel.java, src/main/java/io/vertx/codegen/annotations/DataObject.java, src/main/java/io/vertx/codegen/annotations/JsonGen.java
The `@DataObject` members are deprecated in favour of the `@JsonGen` annotation.
The new `@JsonGen` annotation triggers the generation of a converter and holds the `@DataObject` configuration.
In short:
```java
@DataObject(base64Type = "basic")
```
is replaced by
```java
@DataObject
@JsonGen(base64Type = "basic")
```
=> Add a @JsonGen annotation that replaces the @DataObject converter generation

vertx-codegen-json/src/test/java/io/vertx/test/codegen/converter/DataObjectTest.java, vertx-codegen-json/src/test/java/io/vertx/test/codegen/converter/NoConverter2DataObject.java, vertx-codegen-json/src/test/java/io/vertx/test/codegen/converter/TestDataObject.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/TypeValidator.java, vertx-codegen-processor/src/test/java/io/vertx/test/codegen/ClassTest.java
Objects annotated with @DataObject have the restriction to require a json argument constructor and a toJson() method. Since Vert.x 4 this restriction only useful for service proxies.
This removes this restriction, consequently data objects without a json constructor will be absent from generated fromJson methods when nested inside another data object, likewise data object without a toJson() method will be absent from generated toJson methods.
Rx like generators are not impacted.
=> Remove json constructor/toJson() data object restriction

vertx-codegen-api/src/main/java/module-info.java, vertx-codegen-json/pom.xml, vertx-codegen-json/src/main/resources/META-INF/MANIFEST.MF, vertx-codegen-processor/pom.xml, vertx-codegen-processor/src/main/resources/META-INF/MANIFEST.MF, vertx-codegen-protobuf/pom.xml
The _vertx-codegen-api_ declares its own module descriptor as a `module-info.java` file.
The _vertx-codegen-processor_ and _vertx-codegen-json_ modules instead rely on [moditect](https://github.com/moditect/moditect) to generate module descriptor for the sake of preserving the execution of codegen processor tests in IDE. The codegen processor is not intended to be modular, however _vertx-codegen-api_ and _vertx-codegen-json_ are actually consumed by from java modules (e.g `io.vertx.core` module).
The absence of an module-info descriptor instructs the IDE to run tests in classpath mode which is what we need, hence the moditect is a good fit.
=> JPMS support

vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/type/TypeUse.java, vertx-codegen-processor/src/test/java/io/vertx/test/codegen/ClassNullableTest.java
The codegen processor performs `@Nullable` method override checks, e.g. the compilation fails when `(Future<String>foo)()` overrides `(Future<@Nullable String>)foo()` to ensure that we will not generate incorrect code, e.g. rx cares about this `Maybe`/`Single` are generated depending on the nullability of the argument type of the returned future.
The Java compiler unfortunately does not always provide the annotations for such types, one of them is https://bugs.openjdk.org/browse/JDK-8225377. Fortunately it has been fixed upstream and back-ported to JDK 11 (which is the baseline of this project) unfortunately it makes TypeMirror#toString() (non contractual) behave correctly now (e.g. it will return a different string containing more annotations than before). Unfortunaly the backport was …
=> Remove nullable override method checks

src/main/java/io/vertx/codegen/json/annotations/JsonGen.java
Motivation:
Legacy Buffer base64 encoding stemming from Vert.x 3 is deprecated in Vert.x 4.x
Changes:
Deprecate the base64Type member of the @JsonGen annotation.
=> Deprecate JsonGen base64 encoding basic option

vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/ClassModel.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/TypeValidator.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/type/ApiTypeInfo.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/type/ClassTypeInfo.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/type/EnumTypeInfo.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/type/TypeMirrorFactory.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/type/TypeReflectionFactory.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/type/TypeVariableInfo.java, vertx-codegen-processor/src/test/java/io/vertx/test/codegen/ClassTest.java, vertx-codegen-processor/src/test/java/io/vertx/test/codegen/testapi/javatypes/MethodWithValidJavaTypeParams.java, vertx-codegen-processor/src/test/java/io/vertx/test/codegen/testapi/javatypes/ParameterizedPermittedType.java, vertx-codegen-processor/src/test/java/io/vertx/test/codegen/testapi/javatypes/PermittedType.java
Allow an interface to be annoated with `@GenIgnore(GenIgnore.PERMITTED_TYPE)` to automatically promote a method that declares this type among parameters or return types.
=> Permitted type declarations

vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/ClassModel.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/TypeValidator.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/type/TypeMirrorFactory.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/type/TypeReflectionFactory.java, vertx-codegen-processor/src/main/java/io/vertx/codegen/processor/type/WildcardTypeInfo.java, vertx-codegen-processor/src/tck/java/io/vertx/codegen/testmodel/AnyJavaTypeTCK.java, vertx-codegen-processor/src/tck/java/io/vertx/codegen/testmodel/AnyJavaTypeTCKImpl.java, vertx-codegen-processor/src/test/java/io/vertx/test/codegen/ClassTest.java, vertx-codegen-processor/src/test/java/io/vertx/test/codegen/testapi/javatypes/MethodWithValidJavaTypeParams.java
Motivation:
API sometimes needs to use wildcard declarations processed by RxJava like generators.
Changes:
- simplify the any java type implementation that was more complicated than it had to be
- introduce WildcardTypeInfo created when a wildcard declaration is processed
Result:
Fixes https://github.com/eclipse-vertx/vertx-codegen/issues/63
=> Support wildcard declarations for permitted types

vertx-codegen-json/src/main/java/io/vertx/codegen/json/generator/DataObjectJsonGen.java, vertx-codegen-json/src/test/java/io/vertx/test/codegen/converter/DataObjectTest.java, vertx-codegen-json/src/test/java/io/vertx/test/codegen/converter/TestDataObject.java
Motivation:
The pattern (number, time unit) is often used to express a duration in Vert.x data objects, such as a timeout.
The type `java.time.Duration` is a good alternative and can be used to express the same property in a better fashion.
=> Add support for java.time.Duration as part of the JSON generator
